apiVersion: v1
kind: Secret
metadata:
  name: serviceclock-secrets
type: Opaque
data:
  JWT_SECRET: ${JWT_SECRET}
  STORAGE_CONNECTION_STRING: ${STORAGE_CONNECTION_STRING}
  DBCONN: ${DBCONN}
  METRICS_PASSWORD: ${METRICS_PASSWORD}
  BLOB_CONTAINER: ${BLOB_CONTAINER}
  PRIVATE_BLOB_CONTAINER: ${PRIVATE_BLOB_CONTAINER}
  TOKEN_EXPIRES: ${TOKEN_EXPIRES}
  BASE_URL: ${BASE_URL}
