apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceclock-backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceclock-backend-api
  template:
    metadata:
      labels:
        app: serviceclock-backend-api
    spec:
      containers:
        - name: serviceclock-backend-api
          image: ${DOCKER_USERNAME}/serviceclock_backend_api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: serviceclock-secrets
