services:
  serviceclock_backend_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "7267:8080"
    env_file:
      - Envs/dev.env
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - .:/app
    networks:
      - serviceclock
    depends_on:
      - serviceclock_db
  
  serviceclock_db:
    image: postgres:latest
    restart: always
    ports:
      - 5548:5432
    networks:
      - serviceclock
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  
  serviceclock_prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./Envs/metrics_token:/etc/prometheus/secrets/metrics_token
    ports:
      - "9090:9090" 
    networks:
      - serviceclock
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  serviceclock:

volumes:
  postgres-data: