global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'serviceclock_backend_api'
    static_configs:
      - targets: ['host.docker.internal:7267']
    bearer_token_file: /etc/prometheus/secrets/metrics_token  
