name: CI/CD Pipeline for ServiceClock Backend API

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "METRICS_PASSWORD=${{ secrets.METRICS_PASSWORD }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "STORAGE_CONNECTION_STRING=${{ secrets.STORAGE_CONNECTION_STRING }}" >> $GITHUB_ENV
          echo "DBCONN=${{ secrets.DBCONN }}" >> $GITHUB_ENV
          echo "BLOB_CONTAINER=${{ secrets.BLOB_CONTAINER }}" >> $GITHUB_ENV
          echo "PRIVATE_BLOB_CONTAINER=${{ secrets.PRIVATE_BLOB_CONTAINER }}" >> $GITHUB_ENV
          echo "TOKEN_EXPIRES=${{ secrets.TOKEN_EXPIRES }}" >> $GITHUB_ENV
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Docker Login
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker image
        run: |
          docker-compose -f src/docker-compose.yml build

      - name: Push Docker image
        run: |
          # Defina o nome completo do repositório no Docker Hub
          docker tag serviceclock_backend_api:latest $DOCKER_USERNAME/serviceclock_backend_api:latest
          docker push $DOCKER_USERNAME/serviceclock_backend_api:latest


      - name: Tag Docker image
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker tag serviceclock_backend_api:latest ${{ secrets.DOCKER_USERNAME }}/serviceclock_backend_api:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV 

      - name: Replace BASE_URL in ingress.yml
        run: |
          sed -i 's|${BASE_URL}|'"${{ secrets.BASE_URL }}"'|g' src/Kube/service-clock.ingress.yml

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubectl-version: 'latest'

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      
      - name: Encode secrets to base64 and replace in yaml
        run: |
          export JWT_SECRET_BASE64=$(echo -n $JWT_SECRET | base64)
          export STORAGE_CONNECTION_STRING_BASE64=$(echo -n $STORAGE_CONNECTION_STRING | base64)
          export DBCONN_BASE64=$(echo -n $DBCONN | base64)
          export METRICS_PASSWORD_BASE64=$(echo -n $METRICS_PASSWORD | base64)
          export BLOB_CONTAINER_BASE64=$(echo -n $BLOB_CONTAINER | base64)
          export PRIVATE_BLOB_CONTAINER_BASE64=$(echo -n $PRIVATE_BLOB_CONTAINER | base64)
          export TOKEN_EXPIRES_BASE64=$(echo -n $TOKEN_EXPIRES | base64)
          export BASE_URL_BASE64=$(echo -n $BASE_URL | base64)

          # Substituindo as variáveis no arquivo YAML com escape para caracteres especiais
          sed -i "s|\${JWT_SECRET}|$(printf '%s' "$JWT_SECRET_BASE64" | sed 's/[&/\]/\\&/g')|g" src/Kube/service-clock.secrets.yml
          sed -i "s|\${STORAGE_CONNECTION_STRING}|$(printf '%s' "$STORAGE_CONNECTION_STRING_BASE64" | sed 's/[&/\]/\\&/g')|g" src/Kube/service-clock.secrets.yml
          sed -i "s|\${DBCONN}|$(printf '%s' "$DBCONN_BASE64" | sed 's/[&/\]/\\&/g')|g" src/Kube/service-clock.secrets.yml
          sed -i "s|\${METRICS_PASSWORD}|$(printf '%s' "$METRICS_PASSWORD_BASE64" | sed 's/[&/\]/\\&/g')|g" src/Kube/service-clock.secrets.yml
          sed -i "s|\${BLOB_CONTAINER}|$(printf '%s' "$BLOB_CONTAINER_BASE64" | sed 's/[&/\]/\\&/g')|g" src/Kube/service-clock.secrets.yml
          sed -i "s|\${PRIVATE_BLOB_CONTAINER}|$(printf '%s' "$PRIVATE_BLOB_CONTAINER_BASE64" | sed 's/[&/\]/\\&/g')|g" src/Kube/service-clock.secrets.yml
          sed -i "s|\${TOKEN_EXPIRES}|$(printf '%s' "$TOKEN_EXPIRES_BASE64" | sed 's/[&/\]/\\&/g')|g" src/Kube/service-clock.secrets.yml
          sed -i "s|\${BASE_URL}|$(printf '%s' "$BASE_URL_BASE64" | sed 's/[&/\]/\\&/g')|g" src/Kube/service-clock.secrets.yml




      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f src/Kube/service-clock.secrets.yml
          kubectl apply -f src/Kube/service-clock.deployment.yml
          kubectl apply -f src/Kube/service-clock.service.yml
          kubectl apply -f src/Kube/service-clock.ingress.yml
          kubectl rollout status deployment/serviceclock-backend-api 

      - name: Verify Kubernetes deployment
        run: |
          kubectl get pods -l app=serviceclock-backend-api
