name: CI/CD Pipeline for ServiceClock Backend API

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "METRICS_PASSWORD=${{ secrets.METRICS_PASSWORD }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "STORAGE_CONNECTION_STRING=${{ secrets.STORAGE_CONNECTION_STRING }}" >> $GITHUB_ENV
          echo "DBCONN=${{ secrets.DBCONN }}" >> $GITHUB_ENV
          echo "BLOB_CONTAINER=${{ secrets.BLOB_CONTAINER }}" >> $GITHUB_ENV
          echo "PRIVATE_BLOB_CONTAINER=${{ secrets.PRIVATE_BLOB_CONTAINER }}" >> $GITHUB_ENV
          echo "TOKEN_EXPIRES=${{ secrets.TOKEN_EXPIRES }}" >> $GITHUB_ENV
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV

      - name: Set environment variables files
        run: |
          envsubst < src/Kube/service-clock.service.yml > src/Kube/service-clock.service.tmp.yml
          envsubst < src/Kube/service-clock.ingress.yml > src/Kube/service-clock.ingress.tmp.yml
          envsubst < src/Kube/service-clock.deployment.yml > src/Kube/service-clock.deployment.tmp.yml

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Docker Login
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker image
        run: |
          docker-compose -f src/docker-compose.yml build

      - name: Push Docker image
        run: |
          docker tag serviceclock_backend_api:latest $DOCKER_USERNAME/serviceclock_backend_api:latest
          docker push $DOCKER_USERNAME/serviceclock_backend_api:latest


      - name: Tag Docker image
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker tag serviceclock_backend_api:latest ${{ secrets.DOCKER_USERNAME }}/serviceclock_backend_api:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV 

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubectl-version: 'latest'

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f src/Kube/service-clock.deployment.tmp.yml
          kubectl apply -f src/Kube/service-clock.service.tmp.yml
          kubectl apply -f src/Kube/service-clock.ingress.tmp.yml
          kubectl rollout status deployment/serviceclock-backend-api 

      - name: Verify Kubernetes deployment
        run: |
          kubectl get pods -l app=serviceclock-backend-api
