name: CI/CD Pipeline for ServiceClock Backend API

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set environment variables and encode secrets to base64
        run: |
          chmod +x .github/workflows/encode_and_replace.sh
          .github/workflows/encode_and_replace.sh

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Docker Login
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker image
        run: |
          docker-compose -f src/docker-compose.yml build

      - name: Push Docker image
        run: |
          # Defina o nome completo do repositório no Docker Hub
          docker tag serviceclock_backend_api:latest $DOCKER_USERNAME/serviceclock_backend_api:latest
          docker push $DOCKER_USERNAME/serviceclock_backend_api:latest


      - name: Tag Docker image
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker tag serviceclock_backend_api:latest ${{ secrets.DOCKER_USERNAME }}/serviceclock_backend_api:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV 

      - name: Replace BASE_URL in ingress.yml
        run: |
          sed -i 's|${BASE_URL}|'"${{ secrets.BASE_URL }}"'|g' src/Kube/service-clock.ingress.yml

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubectl-version: 'latest'

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f src/Kube/service-clock.secrets.yml
          kubectl apply -f src/Kube/service-clock.deployment.yml
          kubectl apply -f src/Kube/service-clock.service.yml
          kubectl apply -f src/Kube/service-clock.ingress.yml
          kubectl rollout status deployment/serviceclock-backend-api 

      - name: Verify Kubernetes deployment
        run: |
          kubectl get pods -l app=serviceclock-backend-api
